### ISSUE TITLE
CRITICAL: Huge CPU usage when using library

### ISSUE THREAD

**Issue by joeywittig** [arturograu/country_flags#13]

**Comment by arturograu** [comment]
Hi @joeywittig . Thank you for your issue report. I tested the library and I am not having such issue.

Can you provide with more details on how to reproduce the issue or some more information about it?

Thank you!

**Comment by bgoncharuck** [comment]
Hello @joeywittig,

Leveraging country flags can pose significant challenges to system resources, primarily due to the intricate nature of handling both PNG and SVG formats. This demands a meticulous approach that often proves to be a laborious task.

Regarding CPU usage concerns, have you encountered similar challenges solely with this library, or have you observed similar patterns with other libraries as well? Your insights would be invaluable in gauging the broader impact of these issues.
